import cv2 as cv
img1 = cv.imread("Lighthouse.jpg",0)
img2 = cv.imread("kangaroo.jpg",0)
img3 = cv.imread("galaxy.jpg",0)
img4 = cv.imread("Moon sinking, sun rising.jpg",0)
img5 = cv.resize(img1,(100,100))
img6 = cv.resize(img2,(100,100))
img7 = cv.resize(img3,(100,100))
img8 = cv.resize(img4,(100,100))
cv.imwrite("resized_lightHouse.jpg",img8)
cv.imwrite("resized_galaxy.jpg",img5)
cv.imwrite("resized_kangaroo.jpg",img6)
cv.imwrite("resized_Moonsinking,sunrising.jpg",img7)
cv.imshow("resized_lightHouse",img8)
cv.imshow("resized_galaxy",img1)
cv.imshow("resized_kangaroo",img2)
cv.imshow("resized_Moonsinking,sunrising",img3)
cv.waitKey(0)
